title: Warrnambool Symphony Orchestra
email: info@warrnamboolorchestra.org.au
description: >-
  Warrnambool Symphony Orchestra Ltd is an incorporated, not-for-profit association governed by
  a representative committee elected at the Annual General Meeting.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
facebook_username: "warrnamboolorchestra"
youtube_username: "@warrnamboolorchestra"

# Build settings
theme: minima
plugins:
  - jekyll-feed


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
